# Solving System of Linear Equations using Row Reduction

In [2]:
import numpy as np

### Preparation for Row Reduction

In [3]:
A = np.array([
        [2, -1, 4],
        [4, 6, 7],
        [-1, 2, -3]
    ], dtype=np.dtype(float))

b = np.array([-5, 2, 15], dtype=np.dtype(float))

In [4]:
A_system = np.hstack((A, b.reshape((3, 1))))

print(A_system)

[[ 2. -1.  4. -5.]
 [ 4.  6.  7.  2.]
 [-1.  2. -3. 15.]]


### Elementary Operations

In [5]:
def MultiplyRow(M, row_num, row_num_multiple):
    M_new = M.copy()
    M_new[row_num] = M_new[row_num] * row_num_multiple
    return M_new

print("Original matrix:")
print(A_system)
print("\nMatrix after its second row is multiplied by 3:")
print(MultiplyRow(A_system,1,3))

Original matrix:
[[ 2. -1.  4. -5.]
 [ 4.  6.  7.  2.]
 [-1.  2. -3. 15.]]

Matrix after its second row is multiplied by 3:
[[ 2. -1.  4. -5.]
 [12. 18. 21.  6.]
 [-1.  2. -3. 15.]]


In [6]:
def AddRows(M, row_num_1, row_num_2, row_num_1_multiple):
    M_new = M.copy()
    M_new[row_num_2] = row_num_1_multiple * M_new[row_num_1] + M_new[row_num_2]
    return M_new

print("Original matrix:")
print(A_system)
print("\nMatrix after exchange of the third row with the sum of itself and second row multiplied by 1/2:")
print(AddRows(A_system,1,2,1/2))

Original matrix:
[[ 2. -1.  4. -5.]
 [ 4.  6.  7.  2.]
 [-1.  2. -3. 15.]]

Matrix after exchange of the third row with the sum of itself and second row multiplied by 1/2:
[[ 2.  -1.   4.  -5. ]
 [ 4.   6.   7.   2. ]
 [ 1.   5.   0.5 16. ]]


In [7]:
def SwapRows(M, row_num_1, row_num_2):
    M_new = M.copy()
    M_new[[row_num_1, row_num_2]] = M_new[[row_num_2, row_num_1]]
    return M_new

print("Original matrix:")
print(A_system)
print("\nMatrix after exchange its first and third rows:")
print(SwapRows(A_system,0,2))

Original matrix:
[[ 2. -1.  4. -5.]
 [ 4.  6.  7.  2.]
 [-1.  2. -3. 15.]]

Matrix after exchange its first and third rows:
[[-1.  2. -3. 15.]
 [ 4.  6.  7.  2.]
 [ 2. -1.  4. -5.]]
