# Numpy Arrays

## How to Create Numpy Array?

In [3]:
# import numpy arrays
import numpy as np

In [7]:
# array containing the elements 1, 2,3,4.
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


Another way to implement an array is using np.arange()

In [10]:
b = np.arange(3)
print(b)

[0 1 2]


In [14]:
c = np.arange(1, 20, 3)
print(c)

[ 1  4  7 10 13 16 19]


an array with five evenly spaced values in the interval from 0 to 100 using np.linspace()

In [20]:
lin_spaced_arr = np.linspace(0, 100, 5)
print(lin_spaced_arr)

[  0.  25.  50.  75. 100.]


In [21]:
lin_spaced_arr_int = np.linspace(0, 100, 5, dtype=int)
print(lin_spaced_arr_int)

[  0  25  50  75 100]


In [22]:
c_int = np.arange(1, 20, 3, dtype=int)
print(c_int)

[ 1  4  7 10 13 16 19]


In [23]:
b_float = np.arange(3, dtype=float)
print(b_float)

[0. 1. 2.]


In [26]:
char_arr = np.array(['Zeeshan Ahmad'])
print(char_arr)

['Zeeshan Ahmad']


**Some BuiltIn Functions**

np.ones() - Returns a new array setting values to one.

np.zeros() - Returns a new array setting values to zero.

np.empty() - Returns a new uninitialized array.

np.random.rand() - Returns a new array with values chosen at random.

In [27]:
ones_arr = np.ones(3)
print(ones_arr)

[1. 1. 1.]


In [28]:
zeros_arr = np.zeros(3)
print(zeros_arr)

[0. 0. 0.]


In [29]:
empt_arr = np.empty(3)
print(empt_arr)

[0. 0. 0.]


In [31]:
rand_arr = np.random.rand(3)
print(rand_arr)

[0.60218012 0.37601113 0.02421398]
