# Numpy Arrays

## How to Create Numpy Array?

In [3]:
# import numpy arrays
import numpy as np

In [7]:
# array containing the elements 1, 2,3,4.
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


Another way to implement an array is using np.arange()

In [10]:
b = np.arange(3)
print(b)

[0 1 2]


In [14]:
c = np.arange(1, 20, 3)
print(c)

[ 1  4  7 10 13 16 19]


an array with five evenly spaced values in the interval from 0 to 100 using np.linspace()

In [20]:
lin_spaced_arr = np.linspace(0, 100, 5)
print(lin_spaced_arr)

[  0.  25.  50.  75. 100.]


In [21]:
lin_spaced_arr_int = np.linspace(0, 100, 5, dtype=int)
print(lin_spaced_arr_int)

[  0  25  50  75 100]


In [22]:
c_int = np.arange(1, 20, 3, dtype=int)
print(c_int)

[ 1  4  7 10 13 16 19]


In [23]:
b_float = np.arange(3, dtype=float)
print(b_float)

[0. 1. 2.]


In [26]:
char_arr = np.array(['Zeeshan Ahmad'])
print(char_arr)

['Zeeshan Ahmad']


**Some BuiltIn Functions**

np.ones() - Returns a new array setting values to one.

np.zeros() - Returns a new array setting values to zero.

np.empty() - Returns a new uninitialized array.

np.random.rand() - Returns a new array with values chosen at random.

In [27]:
ones_arr = np.ones(3)
print(ones_arr)

[1. 1. 1.]


In [28]:
zeros_arr = np.zeros(3)
print(zeros_arr)

[0. 0. 0.]


In [29]:
empt_arr = np.empty(3)
print(empt_arr)

[0. 0. 0.]


In [31]:
rand_arr = np.random.rand(3)
print(rand_arr)

[0.60218012 0.37601113 0.02421398]


# Multidimensional Arrays

In [33]:
#2 dimensional array 
two_dim_arr = np.array([[1,2,3], [4,5,6]])
print(two_dim_arr)

[[1 2 3]
 [4 5 6]]


In [35]:
# 1-D array 
one_dim_arr = np.array([1, 2, 3, 4, 5, 6])

# Multidimensional array using reshape()
multi_dim_arr = np.reshape(
                one_dim_arr, 
               (2,3) 
              )
# Print 
print(multi_dim_arr)

[[1 2 3]
 [4 5 6]]


## Finding size, shape and dimension

ndarray.ndim - Stores the number dimensions of the array.

ndarray.shape - Stores the shape of the array. Each number in the tuple denotes the lengths of each corresponding dimension.

ndarray.size - Stores the number of elements in the array.

In [37]:
# Dimension of the 2-D array multi_dim_arr
multi_dim_arr.ndim

2

In [39]:
# Shape of the 2-D array multi_dim_arr
multi_dim_arr.shape

(2, 3)

In [40]:
# Size of the array multi_dim_arr
multi_dim_arr.size

6

# Math operations

In [41]:
arr_1 = np.array([2, 4, 6])
arr_2 = np.array([1, 3, 5])

# Adding 
addition = arr_1 + arr_2
print(addition)

# Subtracting 
subtraction = arr_1 - arr_2
print(subtraction)

# Multiplying 
multiplication = arr_1 * arr_2
print(multiplication)

[ 3  7 11]
[1 1 1]
[ 2 12 30]


### Multiplying vector with a scalar (broadcasting)

In [42]:
vector = np.array([1, 2])
vector * 1.6

array([1.6, 3.2])

# Indexing and slicing

### Indexing

In [43]:
# third element 
a = ([1, 2, 3, 4, 5])
print(a[2])

# first element
print(a[0])

3
1


In [44]:
# Indexing 2-D array
two_dim = np.array(([1, 2, 3],
          [4, 5, 6], 
          [7, 8, 9]))

print(two_dim[2][1])

8


### Slicing

In [46]:
# Slicing 1-D array
sliced_arr = a[1:4]
print(sliced_arr)

[2, 3, 4]


In [47]:
sliced_arr = a[:3]
print(sliced_arr)

[1, 2, 3]


In [48]:
sliced_arr = a[2:]
print(sliced_arr)

[3, 4, 5]


In [49]:
print(a == a[:] == a[::])

True


In [50]:
sliced_arr_1 = two_dim[0:2]
sliced_arr_1

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
sliced_two_dim_rows = two_dim[1:3]
print(sliced_two_dim_rows)

[[4 5 6]
 [7 8 9]]


In [52]:
sliced_two_dim_cols = two_dim[:,1]
print(sliced_two_dim_cols)

[2 5 8]
