# Linear Systems as Matrics

In [1]:
#import numpy
import numpy as np

In [2]:
# Coefficient matrix (A)
A = np.array([
        [-2, 4],
        [3, 2]
    ])

# Constants matrix (B)

b = np.array([7, 1])

print("Matrix A:")
print(A)
print("\nArray b:")
print(b)

Matrix A:
[[-2  4]
 [ 3  2]]

Array b:
[7 1]


In [3]:
print(f"Shape of A: {A.shape}")
print(f"Shape of b: {b.shape}")

Shape of A: (2, 2)
Shape of b: (2,)


In [4]:
# Solve for X (X = A⁻¹ * B)
X = np.linalg.solve(A, b)

In [5]:
print("Solution for the system of equations:")
print(f"x = {X[0]:.2f}, y = {X[1]:.2f}")

Solution for the system of equations:
x = -0.63, y = 1.44


# Determinant of a Matrix

In [6]:
d = np.linalg.det(A)

print(f"Determinant of matrix A: {d:.2f}")

Determinant of matrix A: -16.00


# Visualizing 2x2 Systems as Plotlines

### Representation of the system as a matrix

In [7]:
A_system = np.hstack((A, b.reshape((2, 1))))

print(A_system)

[[-2  4  7]
 [ 3  2  1]]


In [8]:
print(A_system[1])

[3 2 1]


### System of Linear Equations with No Solutions

In [14]:
A_2 = np.array([
        [-1, 3],
        [3, -9]
    ], dtype=np.dtype(float))

b_2 = np.array([7, 1], dtype=np.dtype(float))

d_2 = np.linalg.det(A_2)

print(f"Determinant of matrix A_2: {d_2:.2f}")

Determinant of matrix A_2: 0.00


In [15]:
try:
    x_2 = np.linalg.solve(A_2, b_2)
except np.linalg.LinAlgError as err:
    print(err)

Singular matrix


In [16]:
A_2_system = np.hstack((A_2, b_2.reshape((2, 1))))
print(A_2_system)

[[-1.  3.  7.]
 [ 3. -9.  1.]]


### System of Linear Equations with an Infinite Number of Solutions

In [17]:
b_3 = np.array([7, -21], dtype=np.dtype(float))

In [18]:
A_3_system = np.hstack((A_2, b_3.reshape((2, 1))))
print(A_3_system)

[[ -1.   3.   7.]
 [  3.  -9. -21.]]
